### ISSUE TITLE
Graph screen tweeks

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#138]
1. Could the farm drop down populate the farm name automatically when a site is selected.

![image](https://user-images.githubusercontent.com/50975792/85337371-712e2d80-b534-11ea-82b3-49f3fc6ef54f.png)

2. Could the MM/HR be changed to    'mm'  and  'Hours' be placed on the line above by the days.
![image](https://user-images.githubusercontent.com/50975792/85337535-c5d1a880-b534-11ea-8f32-af5e7da44ce6.png)

3. Same with this one  (mms)  to 'mm' and MM's/plant to 'mm/plant'
Can please put     'Season to date mm'
![image](https://user-images.githubusercontent.com/50975792/85337803-409ac380-b535-11ea-821f-5e4159857adc.png)

4.Can depth graph boundaries be set to 10% vsw either side of the graph lines 
![image](https://user-images.githubusercontent.com/50975792/85337897-750e7f80-b535-11ea-93bb-1a53ff5e3e66.png)

**Comment by mabbettbyron** [comment]
4: Again is hard. 10% of what. Previous Week, Full Point, Refill?
What I have done is
* the graph starts at This Weeks Minumum VSW value figure - 5
* the graph starts at Full Point Maximum value figure + 2.
It works well for Max as Full Point. But Lower figure can be a bit weird.
