### ISSUE TITLE
Irrigation and rainfall in wrong position on graph

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#140]
Rainfall and irrigation is not displaying on the correct dates. seems about -5 or -6 days out.

![image](https://user-images.githubusercontent.com/50975792/85339326-0ed72c00-b538-11ea-915b-9efe93ee2f8e.png)

**Comment by mabbettbyron** [comment]
This is a tough one. The VSW lines are base on a Time Scale and the rainfall and irrigation are of a Band Scale. Have spent ages on this so parking for now as will need a bit of a rethink in terms of options.

**Comment by Brendanfruition** [comment]
Hi Byron,

Thanks for working through these. I have been abit slammed recently so haven’t done much with Terraprobe. Have allowed a few days towards the end of this week.

Could you send a link to the latest version. My link is no longer working.

Cheers

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D6591F.26AF4FD0]

**Comment by mabbettbyron** [comment]
With Hortplus doing customer facing graphs is this required?
