### ISSUE TITLE
Enhancements  and formatting for Terraprobe

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#143]
Number of requests as below

- Could the recommendation pop up please be moveable to better view the graphs while recommending
1 hour

- Some of the depth graphs are out of scale (Whar 2) Use the minimum of the 3 points- current, previous or refill
1/2 hour

- Could hashed shading be used to show the change between previous and current reading on depth graph
2 hours

- Could the refill and full point lines be named or key
1 hour

- Could the strategy lines (both lower and upper) be shown as dashed lines please
1/2 hour

- Could rootzone (RZ1) be shown on the graph screen  (e.g. RZ1 60cm)
1 hour

- Could the next weeks (7 days) estimated DWU (daily water use) be shown on the graph screen. This will allow us to see the forecast water use for the next 7 days by the tree and make better recommendations.
1 hour

-Reading screen final column spelling change from Effective irridation to 'Effective Irrigation'

**Comment by mabbettbyron** [comment]
All Done.

6 Hours Work.

Will put it on dev soon for you to sign off.

**Comment by mahalsnz** [comment]
Hi Brendan,
This is all done and have updated your system with the changes. Comment
with any changes (eg: Is RootZone and EDWU alright where it is) or close
the ticket if happy.

Cheers
Byron

**Comment by Brendanfruition** [comment]
Hi Byron, looking awsome!
Couple of small things.
- Root zone- could please have (cm) as units
-Est Dwu- Could this please add the next 7 days estimated DWU together so we can see the estimated DWU for the week ahead?

**Comment by mabbettbyron** [comment]
Hi Brendan,
Root Zone - will do
Est DWU. I don't understand, what 7 days is this? Is this from the recommendations?

**Comment by Brendanfruition** [comment]
Hi Byron. 
Re Est DWU.    We use the est DWU for the next 7 days to see how much water the trees are estimated to use between the latest reading and the next upcoming reading (weekly read). We can then recommend irrigation volumes for the week based on this.

Currently is showing est DWU for a single day eg 2.1mm.  
The tree use over the next 7 days would be 2.1 x 7 = **14.7mm** for the 7day period between monitoring of the site

Could be called 'Est 7 day water use'

Cheers

**Comment by mabbettbyron** [comment]
Save for Friday
