### ISSUE TITLE
Recommendation box days

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#144]
Hi Byron. Is it possible to have the days Mon, Tues, Wed, Thurs, Fri, Sat, Sun fixed over the appropriate box as below image in both the graph screen and the Recommendation screen. 

![image](https://user-images.githubusercontent.com/50975792/89363645-d0cb4b80-d724-11ea-9751-f098d5f80cff.png)

**Comment by mabbettbyron** [comment]
Testing Needed

**Comment by Brendanfruition** [comment]
Hi Byron. Looks good.
One last bit. Could **Hours** be added above the top box as the key.
Cheers
![image](https://user-images.githubusercontent.com/50975792/90184120-ba9a4b00-de08-11ea-86fb-429c980f3b8a.png)

**Comment by mahalsnz** [comment]
Done
