### ISSUE TITLE
+Add note

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#145]
Hi Byron,

Could the '+Add note' please display in a box on the graph screen in red similar to attached image so we can see any pertinent notes about the site while viewing the graph
![image](https://user-images.githubusercontent.com/50975792/89364146-f3aa2f80-d725-11ea-8e3c-c558c371d998.png)

Django 3 has some cool admin features. Use list_filter and search_fields in the admin screens for site, critical dates etc (ones that have a lot of data)

**Comment by mabbettbyron** [comment]
Do you still want the entry of the site note like now, but if there is a note display as read only in the graph like you have drawn?

**Comment by Brendanfruition** [comment]
Hi Byron,
Yep sounds good. leave entry the same and read only on the graph screen.
Doesn't have to be displayed like I drew. Whatever works best in terms of display.

**Comment by mabbettbyron** [comment]
2 hours

After entering site note if on graph screen you need to 'refresh' graph to get note.

Updated API for graphs so site note and technician can be used by Hortplus.
