### ISSUE TITLE
Water meter calc issue

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#146]
Hi Byron,

Water meter calcs dont seem to be working correctly on some sites. See attached image. 24/03/20 date is 63935, previous week is 63934 but is displaying as -1 Irr (L).
Have run process water meter and all processes but doesn't seem to affect this.

Is it possible to set up so minus values don't occur. Cant have minus irrigation.

![image](https://user-images.githubusercontent.com/50975792/89465043-949bf780-d7c5-11ea-8d88-3be0cef232b5.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
That -1 figure is from the PRWIN upload, not from processing meter readings from Probe and Neutron files.

From #132, this was done to solve the problem in Terraprobe, we will go over it on Friday and check that it is working properly.

_When it comes to processing the meter reading, if the difference between last week and this week is less than -1, the system will realise that this is a faulty meter and data cannot be derived between the reset and previous meter reading. This will cause zero's for the derived fields that depend on this for that weeks reading._
