### ISSUE TITLE
Admin skeleton tidy up

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#147]
Hi Byron,

Think we have briefly discussed this before. Hopefully my explanation below makes sense! As I start pumping the additional strategies, readings, products etc into Terraprobe it is going to become quite busy with many entries in admin. To make it simpler to navigate is it possible to tidy up the admin skeleton area to have a overriding level and sub levels that expand below this when selected?

Is currently like this 
![image](https://user-images.githubusercontent.com/50975792/89465895-fd37a400-d7c6-11ea-9209-e4d33790ca71.png)

A format with a heading that expand upon selection or click (or similar) would be great
![image](https://user-images.githubusercontent.com/50975792/89466288-a4b4d680-d7c7-11ea-98f7-956e7f79211c.png)
to something like this
![image](https://user-images.githubusercontent.com/50975792/89466486-0aa15e00-d7c8-11ea-9f39-37da4f130808.png)

This would be useful for the following admin areas:
-Calibrations
-Critical dates
-KC readings
-Products
-Readings (this will become super large with all the readings!)
-Strategys

**Comment by mabbettbyron** [comment]
Definitively, just discovered yesterday Django 3 has some cool admin features. Use list_filter and search_fields in the admin screens for site, critical dates etc (ones that have a lot of data).

It might not look like your pictures but we can definitely make it easier for you.

**Comment by mabbettbyron** [comment]
1 Hour - A bit of research went into it and on Friday we can go over where else these would be helpful.
