### ISSUE TITLE
Add Stratey type bug

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#150]
![image](https://user-images.githubusercontent.com/50975792/90212141-ad03b600-de46-11ea-9cea-d15845ff4cfc.png)

While creating new strategy getting following error screen

![image](https://user-images.githubusercontent.com/50975792/90212207-e1777200-de46-11ea-8185-e9190c0e2eca.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
This is what we want to happen, Remember we made the rule that all percentages were between 0 and 1, so 50 percent will be 0.5

**Comment by Brendanfruition** [comment]
Ahh all good. I remember now. Cheers
