### ISSUE TITLE
PRwin reading export upload

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#155]
Hi Byron
Going to start uploading exported prwin site data from last season. File exported as attached.
[S0000007.TXT](https://github.com/mahalsnz/soilmoisture/files/5184855/S0000007.TXT)
Wont upload
![image](https://user-images.githubusercontent.com/50975792/92415563-9e8e8d00-f1ad-11ea-90fd-e621a0e860e1.png)
The link in the wiki goes to a blank page so i compared it to the files in TerraProbe test data. looks the same.
https://github.com/mahalsnz/soilmoisture/blob/master/soil/skeleton/tests/files/S0000071.TXT

**Comment by mahalsnz** [comment]
Hi Brendan,
This took a little time but obvious now and the other ticket adding serial number to site list will solve it.

This is because the Royal Gala site that has the season start end dates is actually the site number 1802 Royal Gala. 

Site number 7 Royal Gala has no critical dates set.

I'll get those changes up there now.

Cheers
Byron

**Comment by Brendanfruition** [comment]
Hi Byron,
Having issue uploading prwin export file still. Have assigned critical dates, season start and end. Seems to accept the file but times out when uploading
[S0000007.TXT](https://github.com/mahalsnz/soilmoisture/files/5241811/S0000007.TXT)

![image](https://user-images.githubusercontent.com/50975792/93528103-eb344e00-f98d-11ea-89a0-c52f8fda312d.png)

**Comment by Brendanfruition** [comment]
Hi Byron,

Prwin file upload from site 7 worked in dev.
The reading data has come through but I cannot run process root zone on the data. Start end season dates are in.
![image](https://user-images.githubusercontent.com/50975792/93939029-45625400-fd7e-11ea-8923-82c134a6c115.png)

![image](https://user-images.githubusercontent.com/50975792/93939164-7b073d00-fd7e-11ea-9cef-edd99be7b822.png)

Cheers

**Comment by mabbettbyron** [comment]
![image](https://user-images.githubusercontent.com/47704202/94188553-a82e2980-fefd-11ea-956e-e045d4539fe3.png)

Now will display the site and season that is the problem. If a site does not have a start and end date it won't calculate rootzones. No in production yet.

**Comment by Brendanfruition** [comment]
Hi Byron,

Most of the prwin files uploaded apart from 60 odd sites.
They all had the same errors as the ones below. Ideas?

![image](https://user-images.githubusercontent.com/50975792/94200811-23e4a200-ff0f-11ea-9428-742d05087846.png)
[S0001325.TXT](https://github.com/mahalsnz/soilmoisture/files/5279213/S0001325.TXT)
[S0001326.TXT](https://github.com/mahalsnz/soilmoisture/files/5279215/S0001326.TXT)
[S0001382.TXT](https://github.com/mahalsnz/soilmoisture/files/5279218/S0001382.TXT)
[S0000678.TXT](https://github.com/mahalsnz/soilmoisture/files/5279220/S0000678.TXT)

**Comment by mabbettbyron** [comment]
Two problems.
Where reading was empty, now zero if empty.
Where no date for Refill and FP, now used Season start date.

**Comment by mabbettbyron** [comment]
Hi Brendan,
In production have uploaded 1325 and 1326 successfully.

678 site number does not exist so that's why the error message Site matching query does not exist.
