### ISSUE TITLE
site numbers on drop downs

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#156]
Hi Byron,
Could you please put the site numbers on the drop down lists in
![image](https://user-images.githubusercontent.com/50975792/92416030-ac451200-f1af-11ea-8c50-1a594dcf2168.png)
and 
![image](https://user-images.githubusercontent.com/50975792/92416058-cd0d6780-f1af-11ea-9c6c-9cda3899da38.png)
same way as you did for
![image](https://user-images.githubusercontent.com/50975792/92416248-b61b4500-f1b0-11ea-8ab9-d80d1a0db20c.png)

Cheers

**Comment by mahalsnz** [comment]
**Done - 1 Hour**

This helped explain bug for #155
