### ISSUE TITLE
Associating Diviner site numbers to serial number/ calibration

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#157]
Hi Byron,
Can we merge the two below admin screens into one so we can select the probe #/serial number in the 'diviners' . All the 'Probe diviners' screen is doing is associating a diviner number with a probe/serial number
![image](https://user-images.githubusercontent.com/50975792/92818013-52488480-f41b-11ea-9001-ba7ce9a4050e.png)
![image](https://user-images.githubusercontent.com/50975792/92818180-84f27d00-f41b-11ea-8cd6-b823070474c5.png)

**Comment by mabbettbyron** [comment]
To test in dev

**Comment by Brendanfruition** [comment]
Hi Byron,

This is looking great. We have entered all the diviner site sites in the dev version. Is it possible to copy this data through to Production version so we don't have to enter it again.

**Comment by mabbettbyron** [comment]
All Done
