### ISSUE TITLE
Diviner upload and probe #/serial number

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#158]
Hi Byron,
Came across an issue with diviner file upload 

![image](https://user-images.githubusercontent.com/50975792/92823196-1dd7c700-f421-11ea-92de-cbf5b06c640f.png)
Hi Byron,

The diviner export file cannot produce a serial number so will not be able to link to the correct site number
In Prwin a secondary function within Prwin converted the diviner file into one able to be read by Prwin after the download from the diviner probe. At this stage it associated via a drop down a serial number/probe number and inserted it into the converted file prior to importing into Prwin database.

![image](https://user-images.githubusercontent.com/50975792/92824122-27adfa00-f422-11ea-9135-559333ca73aa.png)

When diviner upload is selected could a probe serial number drop down be created to associate the two?

Cheers

**Comment by mahalsnz** [comment]
Can you send (or attach) that diviner file so I can give it a go?

**Comment by Brendanfruition** [comment]
Hi Byron,

Diviner file attached.

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D68A74.EDA76BA0]

**Comment by mahalsnz** [comment]
Fixing with work in **#157**
