### ISSUE TITLE
Drop down order

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#159]
Hi Byron,

Would it be possible to have the ordering for all the file structures to run consecutively  e.g. site 1,2,3,4 etc  at present site 2 will show under site 19045.
![image](https://user-images.githubusercontent.com/50975792/92825509-ba02cd80-f423-11ea-8577-3dd9dff0f944.png)

Same with drop down screens please
![image](https://user-images.githubusercontent.com/50975792/92825978-4614f500-f424-11ea-8a7a-7fd651fb92d0.png)

Cheers

**Comment by mabbettbyron** [comment]
**Done 1 hour**
