### ISSUE TITLE
GPS co-ordinates for sites

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#160]
![image](https://user-images.githubusercontent.com/50975792/92855764-c0567100-f446-11ea-9813-fa99db93dd6c.png)
Hi Byron could we please add in a gps co ordinate (lat and long) into the site database so we can geolocate each of the monitoring sites.
Currently we are using google maps to link up the site numbers to an export of the coordinates from google maps to produce the map with traffic light system.
Would be better to have this data attached to the sites in TerraProbe.

Currently there is a GPS position assigned to the farm in the address section but doesn't allow us to assign coordinates to a site.

Cheers

**Comment by mabbettbyron** [comment]
Hi Brendan, I think this is one to discuss with Hortplus, Millar has just requested a 'summary' graph api which I am working on today. I'll create a ticket, but it may be that site lat and long could belong in Portal.
