### ISSUE TITLE
Fruition Summary API for Terraprobe

### ISSUE THREAD

**Issue by mahalsnz** [mahalsnz/soilmoisture#161]
Hi Byron,

If you could please just give us the whole strategy object, as long as it is the one strategy record from the array that applies for the latest monitoring record date.

Need some feed back on this as:

As a simplistic example.

Strategy dates
2/4/2020
26/3/2020

Latest Reading date
27/3/2020

So either:
The next highest one (2/4)

or

The closest (26/3)

Any ideas?

---

We are building a dashboard for the client portal which will display a summary of all properties that the user has access to. For irrigation this means calculating if any sites fall outside of the strategy, meaning that we need the latest monitoring readings and strategy for every irrigation site.

To avoid slamming your API with many requests would it be possible to create a new route that provides summary data for each irrigation site? Below is an example JSON array that would be ideal for us, open to discussion as to what it actually returns.

**Comment by mahalsnz** [comment]
**3 hours** spent so far as this needs a bit of working out.

**Comment by mahalsnz** [comment]
**6 hours** spent so far all as was a little bit tougher than first thought

graphs/api/v1/fruition_summary

**Comment by mabbettbyron** [comment]
This looks good now so going to put to test.

Overall **8 hours** spent
