### ISSUE TITLE
Run process all timeout

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#166]
![image](https://user-images.githubusercontent.com/50975792/94220234-acc60280-ff3c-11ea-8259-042c6ba7ad85.png)
Hi Byron,
I uploaded the bulk of the prwin data. Following error occurred when running all processes.

Cheers

**Comment by mabbettbyron** [comment]
Hi Brendan,
Can we hold off running all processes at once. If we go through the order then it will be easier to identify problems.

At the moment in production there is some sites with no season start and end dates which means proccessrootzones will not work until that is fixed.
