### ISSUE TITLE
Rootzone calculating

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#167]
Hi Byron,

Have imported all Prwin data now thanks.
Been playing around and have noticed that if I make a manual change to a reading- for example I altered the reading in the pic below at depth 2 to 6.7 rather than 16.7.
RZ1 is not recalculating with the change (have run process rootzone)
![image](https://user-images.githubusercontent.com/50975792/94503957-296e1f00-0264-11eb-8bd3-989ffceab47c.png)

Cheers

**Comment by mahalsnz** [comment]
I just made the change to not recalculate rootzones if there is a value for rz1. You can just delete the rz1 value and it will recalculate.

I can reverse that, it's just we do not want to recalculate all readings every time. It was something I was going to bring up tomorrow.

**Comment by Brendanfruition** [comment]
Looking like this is working well now
