### ISSUE TITLE
Add Critical Dates and Full/Refill reading for next season

### ISSUE THREAD

**Issue by mahalsnz** [mahalsnz/soilmoisture#168]
Some SQL to run manually.

Have tested but snapshot DB before running. Also run update all readings to reviewed.

---

We have all of the Prwin Data into Terraprobe and setup correctly for depths etc. All looks good. Only sites with no data (although setup with season start and ends etc) are new sites that we have installed this season.

 

Am now at the stage of creating 2020-21 season so we can start putting in readings we have gathered over the past few weeks. (getting pressure from growers to get some soil moisture readings out to them ASAP)

I cant locate the season wizard on the home page anymore? Did it get relocated?

 
Hi Brendan,
Remember we put that on the back burner until we had a season under way. We can do something manually for now.

Something like,
All Critical Dates from 19-20 season copied to season 20-21. (eg. Just plus one year)

All Full Point and Refill readings from 19-20 season to season 20-21.  (eg. Just plus one year)

Hows that, anything else you can think of? We could look at doing that tomorrow afternoon.

Cheers

**Comment by Brendanfruition** [comment]
Hi Byron,
Sounds like a plan. Can look at doing tomorrow afternoon.

Cheers

**Comment by mabbettbyron** [comment]
**All Done 2 hours** And Season 20-21 under way with a slight adjustment to start dates afterwards.
