### ISSUE TITLE
Data export for portal

### ISSUE THREAD

**Issue by mahalsnz** [mahalsnz/soilmoisture#170]
Morning Byron,
What we need are property(farm) and site details. Does the Terraprobe system link farms/sites access to users?

Property(farm)
 - internal database id
 - fruition identifier (from the comments that Angus has filled in)
 - any other identifiers? eg prwin had a farm number?
 - name
 - owner name or user id linking the farm to a user
 - owner company

Site
 - internal database id
 - fruition site number
 - name

Users?
 - email address
 - what farms or sites they have access too

**Comment by mabbettbyron** [comment]
**All Done 2 Hours**
