### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#171]
Hi Byron,

Following coming up when trying to access 'sites' from admin screen in Prod. All other areas working ok.
Cheers
Brendan
![image](https://user-images.githubusercontent.com/50975792/94869182-4d6a7400-04a1-11eb-85cd-61ec5978746a.png)

**Comment by mabbettbyron** [comment]
I think you may have entered a new site with row spacing or emmiter spacing as zero. The application rate is application_rate = self.emitter_rate / (self.row_spacing * self.emitter_spacing) causing an are.

I'll fix that in database.

One thing. Can any of those values be zero legitimately?

**Comment by mabbettbyron** [comment]
sites' from admin screen in Prod now working.

Let us know about any of those values being zero legitimately?

**Comment by Brendanfruition** [comment]
Hi Byron,

There will be sites that have non fixed irrigation (overheads or traveling irrigators) that could have a 0 listed but I think the calculation relies on the emitter spacing being set to the same as the tree spacings for this calculation to work so I guess no value should be zero.
 
In cases like this the non drip radio button is selected so the irrigation calculation changes

Cheers
Brendan

**Comment by mabbettbyron** [comment]
Ok, We do not have any rules about the non drip radio button and the irrigation calculation yet.

We will have to come up with them and include them in the spreadsheet of formulas first before making the changes.

**Comment by mabbettbyron** [comment]
Will close this and new ticket for non fixed irrigation
