### ISSUE TITLE
Emitter rate on graph screen

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#172]
Hi Byron,

Could we please have the calculated output rate (e.g 3.2mm/hr) for each of the sites displayed on the graph page.
Maybe next to the amount received last week heading. 
Saying (based on an irrigation system application rate of 3.2mm/hr) like below image.
Need this to make accurate irrigation recommendations
![image](https://user-images.githubusercontent.com/50975792/94870911-3d549380-04a5-11eb-8aaa-faf4dfe850cd.png)

Cheers
Brendan

**Comment by Brendanfruition** [comment]
Hi Byron,

Can this be incorporated into the graph screen at the same time as the change to the irri and rainfall graph? 
Is proving to be important for making the recommendations

**Comment by mabbettbyron** [comment]
**Done 1 hour**

**Comment by Brendanfruition** [comment]
Spot on looks good
