### ISSUE TITLE
Season Graph to span entire season and work with only one reading

### ISSUE THREAD

**Issue by mabbettbyron** [mahalsnz/soilmoisture#175]
- Max and min of y axis changed to include vsw readings.
- Have split out bar graph from line graph as time with lines does not work with bars.

**Comment by mabbettbyron** [comment]
**Done 4 hours**

Have moved rain and irrigation to seperate graph.

**Comment by Brendanfruition** [comment]
Hi Byron.
Great thankyou. Could the rainfall and irri graph be scaled to the same bounds seasonal bounds as the soil moisture graph above. need the irrigation and rainfall to line up with the reading dates please.
Also the critical date lines have disappeared.

Cheers

Brendan
