### ISSUE TITLE
Strategy lines not showing

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#177]
Hi Byron,

Seasonal graphs showing the whole season are looking good.
Stratergy line is showing on the graphs but the full and refill lines have disappeared!

![image](https://user-images.githubusercontent.com/50975792/95030716-1351da00-070e-11eb-85b2-70e400f6b73a.png)
Cheers

**Comment by mabbettbyron** [comment]
They are there, they are just tiny! I'll fix that now.

**Comment by mabbettbyron** [comment]
Done
