### ISSUE TITLE
nan reading bug

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#178]
Hi Byron,

Fix for calculating depth readings with less than 3 seems to be working well.
It has thrown up an issue when we upload a neutron probe file.
 Looks like the 0 readings for the depths past the maximum depth and displaying as 'nan'    e.g. only depth 3-8 recorded. Zero recording for 1 and 2 (like in attached file).  Can the zero figures be ignored during upload?
The 'nan' recorded data is not allowing the graphs to display

![image](https://user-images.githubusercontent.com/50975792/95035017-22da1e80-0720-11eb-955e-57ffb3857556.png)
[5 30-09-2020.xlsx](https://github.com/mahalsnz/soilmoisture/files/5324931/5.30-09-2020.xlsx)

**Comment by mabbettbyron** [comment]
All Done. I've tidied up the records that had Nan inserted so all the graphs should be working.
