### ISSUE TITLE
Diviner file upload

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#179]
Hi Byron,

Following coming up when attempting to upload diviner files 
![image](https://user-images.githubusercontent.com/50975792/95036971-ff19d700-0725-11eb-85a9-a88af2a00464.png)

[Diviner Backup 02 Oct 2020 (Pro84).xlsx](https://github.com/mahalsnz/soilmoisture/files/5325030/Diviner.Backup.02.Oct.2020.Pro84.xlsx)
(have saved the attached file as a xlsx rather than the .csv it downloaded as so it can be attached here)

Cheers

**Comment by mabbettbyron** [comment]
Have you select the Back up Diviner option for the file? I tried it and it worked successfully on my system.

**Comment by Brendanfruition** [comment]
Hi Byron,

Yep tried selecting the diviner option but no joy unfortunately
![image](https://user-images.githubusercontent.com/50975792/95139580-50c76d80-07c9-11eb-90da-8a004b7dd557.png)

**Comment by mabbettbyron** [comment]
Initially you sent me a xlsx file, make sure you upload csv files. Also I noticed the time format is different for the backup diviner than the other diviners (7003 and 7777)
Format backup
2/10/2020 13:40,

Format 7003 and 7777 that Terraprobe accepts at the moment
21 May 2019 13:38:52

Can you make the backup the same time format? Best to standardise them. Another thing is there does not seem to be any site assigned to the Backup.

**Comment by Brendanfruition** [comment]
Hi Byron,

Yep had to attach the file as a xlsx as Github doesn’t accept .csv

Ok I see the issue with the format. I will have a look at the diviner unit when the technician comes back in but I am not sure I have the ability to change the formatting of the time/ date in the unit.

cheers

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image001.png@01D69BE0.ACFFC070]

**Comment by Brendanfruition** [comment]
Hi Byron,

Just got hold off both the diviner units.
Both of them are downloading as csv with the time/date format as below
![image](https://user-images.githubusercontent.com/50975792/95145178-16fd6380-07d7-11eb-96b1-eb48a306ee91.png)

**Comment by Brendanfruition** [comment]
Hi Byron,

The file when opened in not pad opens in the correct time date format, but in excel opens in a different format??
![image](https://user-images.githubusercontent.com/50975792/95146462-62fdd780-07da-11eb-9122-f5f767d8e9a9.png)
