### ISSUE TITLE
Graphs not showing

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#180]
Hi Byron,

Graphs not showing for quite a few sites, example site attached 7112. Full, refill and a reading are in for the site.
No graphs for sites in Mr Apple Lawn Road are showing

![image](https://user-images.githubusercontent.com/50975792/95133407-c2012380-07bd-11eb-9667-5b7e119d7f83.png)

Cheers
Brendan

**Comment by mabbettbyron** [comment]
Hi Brendan,
I fixed this one (SN 7112), by deleting a reading record that had a meter value that was on the 2-October and putting the value into the actual reading record on the 1-October. I don;t know why that would happen. Are they entering the meter readings a day after you have uploaded the counts?

**Comment by Brendanfruition** [comment]
Hi Byron, this shouldn't normally happen. I think the field staff have been entering the water meter data either before we have uploaded or the day after. I will stop this from happening going forward
