### ISSUE TITLE
Rootzone not showing on graph screen

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#182]
Hi Byron,

Rootzone is only showing for the odd graph, most are showing no rootzone on the graph screen in the amount received last week data box

![image](https://user-images.githubusercontent.com/50975792/95148506-f71e6d80-07df-11eb-85f0-a4130f2e8139.png)

**Comment by mabbettbyron** [comment]
Easy Fix. It was generated if their was a previous reading. Have moved.
