### ISSUE TITLE
Graph display issue

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#185]
Hi Byron,

Most graphs displaying correctly apart from 5911. bottom seasonal graph looks like the bounds are set too small? only one that looks like this so far
![image](https://user-images.githubusercontent.com/50975792/95692701-2b80a680-0c84-11eb-961b-aece294f2d00.png)
Cheers

Brendan

**Comment by mabbettbyron** [comment]
Hi Brendan,
That Site was mixing the Harvest Estimate critical date that the Apple Standard deficit strategy required.

Hmm, another report showing showing sites missing critical dates based on what strategies they have?

**Comment by Brendanfruition** [comment]
Ahh ok..
Yes another report is in order.

Cheers
