### ISSUE TITLE
Site soft delete

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#187]
Hi Byron,

The soft delete button is working well in Terraprobe.

The soft deleted site data is transferring through to the Hortplus dashboard and showing as blank graphs- can the soft delete withhold the site data?

Cheers

**Comment by mabbettbyron** [comment]
I think you really need to soft delete in Hortplus as well, then you won't even be able to see the site in Portal. Are you able to do that?

**Comment by Brendanfruition** [comment]
Hi Byron,

Will talk to Hortplus.
I think in the hortplus dashboard we can only alter properties, not the individual sites within that property.

Cheers
