### ISSUE TITLE
KC and run daily water use

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#189]
Hi Byron,

We have entered in all the KC data for all monitored crops.
Tried running Daily water use with the following KC error.

![image](https://user-images.githubusercontent.com/50975792/95915993-83461b80-0e04-11eb-956a-ba86dd74cd77.png)

I am wondering if the KC data is not running because some of it is for last season? Should it matter what season it is in as the same dates and % will apply each season?

Cheers

Brendan

**Comment by mabbettbyron** [comment]
Hi Brendan, Will check.

**Comment by mabbettbyron** [comment]
Yep, thats right. I know we agreed the ET readings would be the same each season, is that the same for KC readings?

**Comment by mabbettbyron** [comment]
Looks really easy to filter by day and month so just need confirmation on different KC's for new season?

**Comment by Brendanfruition** [comment]
Hi Byron

Yep if readings will be fixed and not altered at all from now forward

Cheers

Brend

On Oct 14, 2020 12:08 PM, mabbettbyron <notifications@github.com> wrote:

Yep, thats right. I know we agreed the ET readings would be the same each season, is that the same for KC readings?

**Comment by mabbettbyron** [comment]
OK, Will do.

I have had to remove the region filter on KC readings as well as a lot of the farms have not been assigned to the Hawkes Bay region.

I think we need to go back and review both ET and KC in the future as it is different to how PRWin does it and we have not really nailed it down for Terraprobe

**Comment by mabbettbyron** [comment]
Hi Brendan,
Getting a lot of readings that just have meter reading and nothing else. Because they receive no serial number they are hard to spot. Is there any way to stop this?

**Comment by Brendanfruition** [comment]
Hi Byron,

This is the monitoring staff recording the water meter readings for sites they are monitoring that day.
The readings should be uploaded to these later the same day.

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D6A5F2.B7441790]

**Comment by Brendanfruition** [comment]
Yes good idea to review the KC and ET processes to make sure we have them correct.

Cheers
Brendan
