### ISSUE TITLE
Latest reading/ recommendation screen 

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#190]
Hi Byron,

We briefly discussed this last visit.
I think we can use the recommendation review page to allow us to figure out which sites have been monitored and uploaded for each technician on a given day.
This will allow use to go straight to those sites that have had readings done rater than sifting through all the farms and sites to locate them. 

Ideally it would be great to have this list on the dropdown in the graph/ readings screen as 'latest upload' or something similar
![image](https://user-images.githubusercontent.com/50975792/96387847-9cced500-1201-11eb-9888-aa0d4b8a4564.png)

Alternatively from the readings recommendation screen.
If we work form here we will need to have the 'site' number next to the 'site' and have each of the sites link to the graph/ reading screen when clicked on.

Thoughts?

![image](https://user-images.githubusercontent.com/50975792/96387763-09959f80-1201-11eb-882d-62bbf952edb6.png)

**Comment by mabbettbyron** [comment]
Hi Brendan, Yep, forgot about that. I'll have a play around on dev system and come up with something.

**Comment by mabbettbyron** [comment]
**Done 4 hours**

**Comment by Brendanfruition** [comment]
Hi Byron,
This one is awsome. Makes the process of analyzing the graphs and recommending so much simplier.
