### ISSUE TITLE
Irrigation on graph screen displaying liters rather than mm

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#191]
Hi Byron,

Looks like the graph screen is displaying litres/ plant rather than mm
Is 4.98mm of irrigation.   40.6 litres/ plant

![image](https://user-images.githubusercontent.com/50975792/96399370-b1739300-122a-11eb-805b-f46213573b56.png)

**Comment by mabbettbyron** [comment]
Just to confirm, the graph is correct, but the Season to Date Irrigation figure is wrong?

**Comment by Brendanfruition** [comment]
Yep confirm graph is correct.

Cheers
