### ISSUE TITLE
Run Process meter error

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#193]
Hi Byron
Run Process meter error as attached. Ideas?

Cheers
![image](https://user-images.githubusercontent.com/50975792/96534925-332bf500-12ed-11eb-9e7e-5f2b8e2e8b62.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
I belive it's because that site has no irrigation position defined. I've added a check for it now so it will report what sites don't have that if you run that process.

![image](https://user-images.githubusercontent.com/47704202/96626176-9eb4a780-136b-11eb-8dd9-32c7e62245bd.png)
