### ISSUE TITLE
Rainfall, irrigation not displaying on graph screen

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#194]
Hi Byron,

Irrigation mm, litres/plant and hours and rainfall are not displaying on the graph screen 'amount received last week' box
Cheers

![image](https://user-images.githubusercontent.com/50975792/96665327-27a20200-13b1-11eb-8ca0-49a0675c6848.png)

**Comment by mabbettbyron** [comment]
Can we just confirm what last week is?

If you look at last seasons data (say Citrus) you will notice the graph has the data from the second to last weeks date. Is that correct for 'amount received last week'?

**Comment by Brendanfruition** [comment]
Hi Byron

No I dont think it is correct
Should be the amount between the current reading and the previous reading.
Cheers

Brendan

On Oct 23, 2020 11:45 AM, mabbettbyron <notifications@github.com> wrote:

Can we just confirm what last week is?

If you look at last seasons data (say Citrus) you will notice the graph has the data from the second to last weeks date. Is that correct for 'amount received last week'?

**Comment by Brendanfruition** [comment]
Hi Byron,

Sorry crap vague reply to this from my phone. 
Will try to explain better.

Both of these (rainfall, irrigation litres, mm) should be from the most recent calculations- i.e the current water meter reading - the previous reading. Rainfall will be the accumulated total between the latest reading date and the previous date.

The terminology 'last week' is slightly confusing! As the readings are weekly the calculated/ derived data is showing the data between the most recent and pervious reading- hence last week

Cheers

**Comment by mabbettbyron** [comment]
Ok got it. Will make that change over the weekend.

**Comment by mabbettbyron** [comment]
Hi Brendan,
Actually I don't quite get it.
For Citrus Site season 2019-20, on the graph screen, what should be the figures displayed in the Amount Received Last Week box.
Cheers

**Comment by Brendanfruition** [comment]
Hi Byron,

The Irrigation should be 17.57mm and the rainfall 33.6mm.
This is the data recorded and derived from processes run on the same day as the probe reading data.

It covers the time period from 'now' (when the probe reading is uploaded) to the previous reading date before this.

**Comment by Brendanfruition** [comment]
Hey Byron,

This should be showing the data from the latest reading.
![image](https://user-images.githubusercontent.com/50975792/98290970-4807c880-200f-11eb-9cea-66d6ece4ca12.png)

Cheers
