### ISSUE TITLE
Process run rainfall error

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#195]
Hi Byron,

Follwoing error whe running process rainfall.
Have some unsual rainfall coming through for sites on the same properties with the same weatherstations. Some recording 0, some 1.7mm and others 15mm??  Example Mr Apple Thornton sites in Prod.

Cheers 
![image](https://user-images.githubusercontent.com/50975792/96811111-4a4b1e00-1478-11eb-84ff-79d3e3827058.png)

**Comment by mabbettbyron** [comment]
Have requestd Hortplus to look at:

@Mike Also from metwatch I am getting:

urllib3.connectionpool DEBUG    https://hortplus.metwatch.nz:443 "POST /index.php?pageID=wxn_wget_post&serial=aRwMpQ5wmBs9dkqNUdpf0w%2Fn7O2DYmIvVB0yDOLTsXGoy8NQj1Gr0tg%2F7TWa%2F6T0BXruaV6URDel28zoIfXZiw%3D%3D HTTP/1.1" 200 None
skeleton.management.commands.request_to_hortplus DEBUG    response Error processing request: 
Requested rows (91) exceeds row limit in 24 hours (2000). Used rows in last 24 hours (1944)


2 things
Can we pump up that limit for a few weeks while we are getting underway
The api is still sending a 200 response even though an error is being reported. Will be easier to catch and report to terraprobe user if a non 200 is sent

**Comment by mabbettbyron** [comment]
Hortplus has upped the limit, so we should not get this particular error anymore
