### ISSUE TITLE
On Site error

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#197]
Hi Byron,

Getting the following error when submitting a meter reading using the on site screen
Cheers

Brendan
![image](https://user-images.githubusercontent.com/50975792/97217809-b0df8b80-182c-11eb-94ef-035c33573fae.png)

**Comment by mabbettbyron** [comment]
All fixed now.

Note: You can still enter a decimal, but it will be ignored and saved as 30.0
