### ISSUE TITLE
Graph - amount received last week error

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#198]
Hi Byron,
This is only occurring on the odd site.
Looks like the calc for irrigation mm is not right. displaying high. Should be 44.8mm

Cheers
![image](https://user-images.githubusercontent.com/50975792/97245426-e487d900-185f-11eb-8d7f-be2bb196bb25.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
Just checked this and the figure is now 44.8mm. Is this working or do I still need to look into it?
