### ISSUE TITLE
Graph calc or display error?

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#201]
Hi Byron,

This one has me a bit confused. I think the depths are showing in reverse? 
It appears to be isolated to this one graph?
Cheers

![image](https://user-images.githubusercontent.com/50975792/97641825-adf0cf00-1aa8-11eb-809c-b9677f08a95c.png)

**Comment by mabbettbyron** [comment]
Hi Brendan,
It looks fine to me. What do you mean 'depths are showing in reverse?'

One thing I did notice is that the first reading is for probe 50616, (and the counts go from high to low). And the last two readings are for probe 708 (and the counts go from low to high)

**Comment by Brendanfruition** [comment]
Hi Byron,

Yes what you said. The count appear to be reversed. 
What I would expect to be depth 1 looks like depth 8 and depth 2 like depth 7.
The probe reading 09-10-20 looks correct.   
22-10 and 30-10 look like they are upside down.

Cheers

**Comment by mabbettbyron** [comment]
Yes, that's how they are loaded. If you look at the reading counts the graph is only displaying what has come out of the probe. You may need to check the probe and the file you uploaded

**Comment by Brendanfruition** [comment]
Hi Byron,

The file format looks good out of the probe download. for this site 7402
1 is the deepest depth and 8 the shallowest as expected in the downloaded reading.
The remainder of the sites with readings from this probe and serial number are looking good as expected- just this one that looks upside down.

I did some quick figures with the means of the depths and something is not adding up correctly.


Cheers


Note | 7402 |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 0 | 0 | 0 | Count | 10/30/20_09:49_AM
2 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8384 | 0.9493 | 8384 | Count | 10/30/20_09:49_AM
3 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 7588 | 0.8591 | 7588 | Count | 10/30/20_09:49_AM
4 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8160 | 0.9239 | 8160 | Count | 10/30/20_09:50_AM
5 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 7560 | 0.856 | 7560 | Count | 10/30/20_09:50_AM
6 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8056 | 0.9121 | 8056 | Count | 10/30/20_09:50_AM
7 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8172 | 0.9253 | 8172 | Count | 10/30/20_09:50_AM
8 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 9876 | 1.1182 | 9876 | Count | 10/30/20_09:50_AM
Note | 7402 |   |   |   |   |   |   |   |   |   |   |  
1 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 0 | 0 | 0 | Count | 10/30/20_09:51_AM
2 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 11024 | 1.2482 | 11024 | Count | 10/30/20_09:51_AM
3 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 7180 | 0.813 | 7180 | Count | 10/30/20_09:51_AM
4 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8328 | 0.9429 | 8328 | Count | 10/30/20_09:51_AM
5 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 10048 | 1.1377 | 10048 | Count | 10/30/20_09:51_AM
6 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 9884 | 1.1191 | 9884 | Count | 10/30/20_09:52_AM
7 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 12816 | 1.4511 | 12816 | Count | 10/30/20_09:52_AM
8 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 14812 | 1.6771 | 14812 | Count | 10/30/20_09:52_AM
Note | 7402 |   |   |   |   |   |   |   |   |   |   |  
1 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8836 | 1.0005 | 8836 | Count | 10/30/20_09:53_AM
2 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 7520 | 0.8514 | 7520 | Count | 10/30/20_09:53_AM
3 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 8672 | 0.9819 | 8672 | Count | 10/30/20_09:53_AM
4 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 9556 | 1.082 | 9556 | Count | 10/30/20_09:53_AM
5 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 12440 | 1.4085 | 12440 | Count | 10/30/20_09:54_AM
6 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 15832 | 1.7926 | 15832 | Count | 10/30/20_09:54_AM
7 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 17288 | 1.9574 | 17288 | Count | 10/30/20_09:54_AM
8 | 1 | EMPTY____ | 0 | 0 | g/cc | 8832 | 15476 | 1.7523 | 15476 | Count | 10/30/20_09:54_AM

![image](https://user-images.githubusercontent.com/50975792/97655796-c40f8700-1aca-11eb-9693-4ee831f93b45.png)

**Comment by mabbettbyron** [comment]
Right. Got it. The last reading of the file was not being reversed, so that it why it was so hard to spot.

I've made the change and updated dev to have that change. Can you test it in dev? I've tested it in  my system and was an easy change but would good to test first and I can get in into production at lunch time.

**Comment by Brendanfruition** [comment]
Hi Byron,
Was it doing it just for this site or all?
Im unsure with this site, doesn't look like I would expect. maybe would be better to talk about next time we catch up

Cheers
