### ISSUE TITLE
Irrigation/ effective irrigation calc issues

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#207]
Hi Byron

The following sites aren’t calculating properly:
636, 672, 656, 1800 – Not calculating irrigation
75, 74, 76 – Not calculating effective rainfall/effective irrigation
542 – Not calculating irrigation

Most of these are sites that have non fixed irrigation. 
The calc appears to be working for most of the non fixed irrigation sites, just not those above.

Cheers
Brendan

**Comment by mabbettbyron** [comment]
Hi Brendan,
I think I got it, it was hard to track down, but easy to fix.

Can you just check the calculation for 636 against the below. to see if its not correct. IF so I will put it into prod.

![image](https://user-images.githubusercontent.com/47704202/102020186-50a4a900-3ddc-11eb-8b96-80d634fc57ba.png)

**Comment by Brendanfruition** [comment]
Hi Byron,

Calcs dont look correct I think. 
Looking at the data only 21-10-2020 should show any irrigation.
It should be 

**Irri (mm)**
If meter - rain is more than 0 then,
(Meter- rain)+5=irri(mm)
so
(50-42.7)+5= 12.3 mm

**Irri (L)**
Irri (mm) x (rowspace (m) x plant space (m))= Irri (L)
12.3 x (4.5 x 2.5)= 138 L

**Hrs**
Irri (L)/ application rate= Hrs
138/355=0.38hrs

  |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Non   Fixed Irrigation |   | Inline   Meter | Rain | Irrigation_mms | schedule   ROWSPACE | schedule   PLANTSPACE |   | irrigation_litres | Plant   Spacing | l/plant | Hrs |  
Jazz | 21/05/2019 | 20 | 5.7 | 19.3 | 3.4 | 2.4 |   | 157 | 2.4 | ?? | ?? |  
  | 14/05/2019 | 12 | 3.8 | 13.2 | 3.4 | 2.4 |   | 108 | 2.4 | ?? | ?? |  
  | 07/05/2019 | 0 | 0 | FALSE | 3.4 | 2.4 |   | 0 | 2.4 | ?? | ?? |  
  |   | meter | - rain > 0 | meter-rain+5 | X   rowspace | X   plantspace |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  

Cheers

Brendan

**Comment by mabbettbyron** [comment]
Hi Brendan,
Isn't that site a fixed irrigation (Drip)

![image](https://user-images.githubusercontent.com/47704202/102022751-c36a5000-3ded-11eb-8807-477bfb0085c9.png)

**Comment by mabbettbyron** [comment]
Bug fixed for drip irrigation calculation
