### ISSUE TITLE
Recommendation window bug 

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#208]
Hi Byron,

Have come across a bug when using the recommendation popup on the graph screen.

The Previous weeks comment and hours recommended is coming up nicely and is vey useful.

Issue is: If we delete (no txt at all in window) or use the reset button (no txt at all in window) to do a total clear, the information does not save and the previous recommendation still displays.
If I delete txt (no txt at all in txt window) and alter the hours it will not save the hours change
![image](https://user-images.githubusercontent.com/50975792/100954617-c8bbd500-3579-11eb-91c1-cb95cd3f933b.png)

We have got round this at the moment by entering a . in the recommendation txt screen.

Not entirely sure I have explained this well...

Cheers

**Comment by mabbettbyron** [comment]
Hi Brendan,
I have got this working, but there is a logic that happens (when you clear the recommendation it works, but one it works it will display previous again). I think we can go over this tomorrow in person as it may be easier.

**Comment by mabbettbyron** [comment]
All Done
