### ISSUE TITLE
Critical date changes and strategy changes not showing on graphs

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#213]
Hi Byron,

Have noticed recently if we make a change to the strategy type or a critical date for a site it is not updating on the terraprobe graphs.
•	Example site 1602.
o	Verasion is showing at 11-1-21
o	We have changed to 19-1-21 but remains showing the previous date.

Would it also be possible to show the dates of the critical date lines on the graphs below the line the same as the reading dates

**Comment by mabbettbyron** [comment]
Hi Brendan,
I think it is because of the caching, can you check now to see if it has updated to correct date and let us know. I'll remove the caching for strategy. Is not really needed.

I will add the date to to the critical date lines at the top with the description. It looks best there and does not clog up the reading dates.

**Comment by Brendanfruition** [comment]
Hey Byron,

Sounds good.
I have checked staging and prod and changed some critical dates on # 2 HLZ hops site. No change in the critical date line unfortunately.

Dates at the top by the critical date lines make sense. Good idea.

Cheers

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D6F959.37B0AF60]

**Comment by Brendanfruition** [comment]
Hi Byron,

The CD has changed now on site #2 HLZ hops so guess it is caching?

Cheers

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D6F95C.EDE53FA0]

**Comment by mabbettbyron** [comment]
Hi Brendan,
Sweet, it is caching. I'll make that change early tomorrow morning along with the other changes. Have got a script to automatically update all those longs an lats as well
Cheers
Byron

**Comment by Brendanfruition** [comment]
Hi Byron,

Awesome thanks.
Legend with the lat, long, wasn’t looking forwards to entering them all.

Cheers

Brendan Hamilton
Irrigation Services Manager
Fruition Horticulture HB
0212234218

[cid:image002.png@01D6F96A.FF8DEFF0]
