### ISSUE TITLE
Season Flags for Critical Dates

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#218]
Seasonal flags for Critical dates created aren't always showing, for example "Post Harvest"
Could we get this updated to show?

**Comment by mabbettbyron** [comment]
Hi Brendan,
This one is a bit more complicated.

First I have changed 'Post Harvest' to a a non seasonal flag. The only ones with Seasonal Flag should be 'Start' and 'End'

Secondly, to show on the graph, the critical date must be part of a Strategy. For site 3108 I have added Post Harvest to the Apple Standard deficit. It now shows but off course will affect the strategy lines.

I suppose the questions is, is 'Post Harvest' part of the strategy? Whats it meant to do?

Have a think and a play and we can work out something.

Cheers Byron
