### ISSUE TITLE
Create Test Data Suite

### ISSUE THREAD

**Issue by mahalsnz** [mahalsnz/soilmoisture#23]
Using django's datadump and inputdata create .json files of production like data.

.json files to be checked in so small changes can be made at that level.

Scenarios to create:

- [x] One farm, two sites, two crops, multiple readings to generate a rough graph
- [x] Calibrations and Probe serial numbers. Still need to work out model.
- [x] Other?

**Comment by mabbettbyron** [comment]
See Wiki page for how to.

**Comment by mabbettbyron** [comment]
Also changes to test data now can in ticket of change.
