### ISSUE TITLE
Set up Development Environment on Mac

### ISSUE THREAD

**Issue by mabbettbyron** [mahalsnz/soilmoisture#50]
Check Wiki for:

https://github.com/mahalsnz/soilmoisture/wiki/Development-Build

and

https://github.com/mahalsnz/soilmoisture/wiki/Workflow

and lastly

https://github.com/mahalsnz/soilmoisture/wiki/Database---Test-Data-and-Backups

**Comment by mlynskey2** [comment]
Development environment set up
