### ISSUE TITLE
Create Database and Data Model

### ISSUE THREAD

**Issue by mahalsnz** [mahalsnz/soilmoisture#9]
Database
- [x] soilmoisture database
- [x] postgres user with admin rights

Data Model
- [x] season
- [x] site
- [x] farm
- [x] readings
- [x] calibration
- [x] probe
- [x] report
- [x] reading type
- [x] season

Run Migration

**Comment by mabbettbyron** [comment]
With Diviner work I think this is done and can close Sprint 2 miliestone as well.
